version: '3'

services:
  api-server:
    container_name: go-api-server
    network_mode: "host"
    build:
     context: .
     dockerfile: Dockerfile
    user: root
    #    ports:
    #     - 8080:8080
